# Generated by Django 4.2.6 on 2023-10-28 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('progress', models.CharField(default='To Do', max_length=200)),
                ('priority', models.CharField(blank=True, max_length=200, null=True)),
                ('duedate', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.CharField(default='on 28/10/2023 at 17:32:50', editable=False, max_length=200)),
                ('edited', models.CharField(default="Task wasn't updated since it's creation", max_length=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
