# Generated by Django 4.2.6 on 2023-10-28 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.CharField(default='on 28/10/2023 at 17:34:24', editable=False, max_length=200),
        ),
    ]
