# Generated by Django 4.2.6 on 2023-10-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tasks_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created',
            field=models.CharField(default='28/10/2023 19:09:54', editable=False, max_length=200),
        ),
    ]
